### ISSUE TITLE
hi, can i ask a question?

### ISSUE THREAD

**Issue by jun0wanan** [MiuLab/QAInfomax#1]
hi，your work can be use in many gpu？

**Comment by rsk25** [comment]
The original code forgot to add `info_loss.mean()` when training with multi-GPU. I made a pull request that doesn't cause errors when running multi GPUs.

**Comment by jun0wanan** [comment]
> The original code forgot to add `info_loss.mean()` when training with multi-GPU. I made a pull request that doesn't cause errors when running multi GPUs.

Thanks
